### ISSUE TITLE
Assume spells with a casting time of 1 bonus action are useful in combat.

### ISSUE THREAD

**Issue by dstein766** [ElfFriend-DnD/foundryvtt-dnd5eCharacterActions#13]
FVTT 0.7.9
DND5E 1.2.4
dnd5eCharacterActions 2.0.0
Character sheet: both native DND5E and Tidy5e 0.4.16

When a spell with a Duration of "Instantaneous" is on the character sheet, it does not show up on the Action tab as expected.  Example settings for Misty Step attached.  (Changing Duration to "1 Minute" causes the spell to render on the Action tab.)
![image](https://user-images.githubusercontent.com/24942951/108748160-21549b80-74f3-11eb-933c-ea59b76d9460.png)

**Comment by akrigline** [comment]
Ah, here is another exception to the assumptions I made about "useful in combat". The current logic is something like:
- Does it do damage (or healing)? 
- Does it have an activation time of 1 reaction?
- If the setting is set, does it have a duration of 1 minute?

Otherwise we don't care about it.

Misty Step definitely is a combat spell and definitely doesn't fit any of those criteria. Going to have to think about that one.

Are there any spells which have an activation time of 1 Bonus Action but do not do damage that are not useful in combat?

Misty Step is useful, Expeditious Retreat is useful, Compelled Duel is useful... I think this rule can be safely implemented.

Thanks for the report!

**Comment by akrigline** [comment]
Interestingly, this will also solve for `Hex` and `Hunter's Mark`! Excellent!
