### ISSUE TITLE
Not all spells are being listed

### ISSUE THREAD

**Issue by naesean** [ElfFriend-DnD/foundryvtt-dnd5eCharacterActions#17]
I'm trying to understand in your code the filters you're applying to spells, but I can't quite grasp it.

There are spells, such as Command and Burning Hands that do not show up in the Actions. It seems to have something to do with the way you are filtering.

Why not show all the prepared spells in the Actions list? Why filter?

**Comment by akrigline** [comment]
I wrote a quick summary of how the current logic is in this issue:
https://github.com/ElfFriend-DnD/foundryvtt-dnd5eCharacterActions/issues/13#issuecomment-783557109

Since then it's been expanded with some settings to optionally include other spells.

Command definitely does slip through the cracks but burning hands should show up.

I think all prepared spells is not the correct solution, the objective isn't too replace the spellbook tab, it's to make a useful summary of common actions for combat (i.e. what the dndbeyond action tab does).

Instead, I think allowing users to pick and choose their own exceptions is going to be the play here (#16). This work is almost complete.
