### ISSUE TITLE
Add option to show all spells with casting time of 1 action, 1 bonus action, or 1 reaction

### ISSUE THREAD

**Issue by benbarbour** [ElfFriend-DnD/foundryvtt-dnd5eCharacterActions#32]
I understand filtering out anything but cantrips as an option some players might want. I don't really understand the logic of only showing spells with a 1 minute duration: what about Mage Armor (8 hour duration) or Command (1 round duration)? Those are valid actions.

I'd like the option to show all spells with a casting time of 1 action, 1 bonus action, or 1 reaction that have available slots or uses remaining (for innate spells) .

**Comment by akrigline** [comment]
Thanks for this feedback, let me try to explain what the thought process so far has been:

The core concept is the idea that the actions list is used for "in combat" only. Players have difficulty remembering all the things they can do in combat already, so I don't want to automatically include spells which are obviously not useful in combat.

The module allows the user to manually toggle any spell/item on or off the action list, while not ideal to miss obviously useful things in the automatic filter, this is the fallback.

The automatic filter's current state is something like this:
- If the user limits to cantrips, exclude any leveled spell.
- Include spells with a casting time of a Bonus Action or Reaction (so that part of your request is done at least)
- Always include a spell with a Damage formula
- If the user wants to include one minute spells, include any spell that has a minute duration

That hits a huge percentage of what I think are the obvious combat spells.

I don't actually think "all with a casting time of 1 action" is useful without further refinement. The vast majority of spells in the system have a casting time of 1 action and I don't want spells like Light, Prestidigitation, Detect Magic, Floating Disk, Skywrite to show up on the action list by default.

You mention two in particular that are good examples of a few combat spells which slip past the automatic filter.
Command in particular is unfortunately lacking. Including things with a duration of 1 round sounds smart though.

Spells in 5e with 1 round duration that aren't already caught in the filter:
- Blade Ward
- Color Spray
- Command
- Message
- Sending
- Transport via Plants
- True Strike

Of those, Sending and Message I would consider "false positives" but the rest look great!

Mage Armor is interesting. Typically I'd not think a caster would cast this in-combat but I can see what you mean. I think further expanding the automatic filter to include spells which have Active Effects that affect Armor Class would be reasonable.
That would catch Shield of Faith and Barkskin as well, assuming the spell is configured per the included SRD compendia.

**Comment by benbarbour** [comment]
Thanks for the detailed response and great reasoning! Maybe put it in the README?

I agree that putting utility spells in there _probably_ isn't desired by most people. I think including everything with an AC active effect (maybe just an Active Effect in general?) would be a good addition, as would extending the duration to include filter to include 1 round or less by default.

**Comment by akrigline** [comment]
Oh my readme apparently reset when I switched build tools... whoops. 😓

**Comment by akrigline** [comment]
Alright this should be included in 4.3.0. The duration of one round is tied to the one minute setting (1 minute or less). And a new config option for including spells with effects by default. Thanks for the feedback!
Also fixed the readme :P
